name: Validate Gitops Manifests

on:
  push:
    branches:
      - main

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy Config Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-dir: './apps'
          severity: 'CRITICAL,HIGH'
